application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 604800000 # 7 days
      refresh-token:
        expiration: 2678400000 # 31 days

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/mydatabase
    username: myuser
    password: secret
  mvc:
    log-request-details: true
  threads:
    virtual:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
springdoc:
  swagger-ui:
    tags-sorter: alpha
  writer-with-order-by-keys: true

