application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  mvc:
    log-request-details: true
  data:
    mongodb:
      host: localhost
      database: 'pz'
      port: 27017
      username: michal
      password: michal2115
      authentication-database: admin

logging:
  level:
    org:
      springframework:
        security: DEBUG
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG